# FROM node:22-alpine

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 5173
# # CMD ["npm", "run", "dev", "--", "--host"]
# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--force"]






# Build React/Vite app
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Serve with nginx (fast & stable)
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]