# k8s/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173        # service listens on 5173
      targetPort: 5173  # pod container port (Vite)
      nodePort: 30008