apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80         # service ka internal port (frontend ke liye)
      targetPort: 80   # ← ye change karo (pod ka port)
      nodePort: 30008     # optional, Minikube auto assign karega agar hata do